# Generated by Django 3.2.3 on 2021-06-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_funball.gameweek')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('home_score', models.IntegerField()),
                ('away_team', models.CharField(max_length=20)),
                ('away_score', models.IntegerField()),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_funball.gameday')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.JSONField()),
                ('funballer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_funball.funballer')),
            ],
        ),
    ]
