# Generated by Django 3.2.3 on 2021-07-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('player_points', models.IntegerField()),
                ('team_points', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('gameweek_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('home_score', models.IntegerField()),
                ('away_team', models.CharField(max_length=20)),
                ('away_score', models.IntegerField()),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameday')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.team')),
            ],
        ),
        migrations.AddField(
            model_name='gameday',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_funball.gameweek'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('kickoff', models.CharField(max_length=20)),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameday')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funballer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.funballer')),
                ('gameweek_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameweek')),
                ('player_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.player')),
                ('team_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.team')),
            ],
        ),
    ]
