# Generated by Django 3.2.3 on 2021-08-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('player_points', models.IntegerField()),
                ('team_points', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pin', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gameday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('gameweek_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('FORWARD', 'Forward')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('assists', models.ManyToManyField(related_name='assists', to='fantasy_funball.Player')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_away_team', to='fantasy_funball.team')),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameday')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_home_team', to='fantasy_funball.team')),
                ('scorers', models.ManyToManyField(related_name='scorers', to='fantasy_funball.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.team'),
        ),
        migrations.AddField(
            model_name='gameday',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameweek'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.CharField(max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_away_team', to='fantasy_funball.team')),
                ('gameday', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameday')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_home_team', to='fantasy_funball.team')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_processed', models.BooleanField(default=False)),
                ('funballer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.funballer')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.gameweek')),
                ('player_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.player')),
                ('team_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.team')),
            ],
        ),
    ]
