# Generated by Django 3.2.3 on 2021-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_funball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameweekSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='player_has_been_steved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choices',
            name='team_has_been_steved',
            field=models.BooleanField(default=False),
        ),
    ]
