# Generated by Django 3.2.3 on 2021-06-11 20:43

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_funball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', djongo.models.fields.JSONField()),
                ('funballer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_funball.funballer')),
            ],
        ),
    ]
