# Generated by Django 3.2.3 on 2021-09-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_funball', '0002_auto_20210907_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='result',
            name='scorers',
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.result')),
            ],
        ),
        migrations.CreateModel(
            name='Assists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assists_made', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fantasy_funball.result')),
            ],
        ),
    ]
