name: Lint Fantasy Funball

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Flake8 & Black
      run: pip install flake8 black

    - name: Run Flake8
      run:  python -m flake8 --benchmark fantasy_funball/;

    - name: Run Black
      run: python -m black --check fantasy_funball;
  