name: Test Fantasy Funball - Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install poetry
        poetry export --with dev -f requirements.txt --output requirements.txt --without-hashes
        pip install --no-cache-dir -r requirements.txt

    - name: Unit tests
      run: pytest fantasy_funball/
