name: Test Fantasy Funball

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker stack
      run: docker-compose build

    - name: Unit tests
      run: pytest fantasy_funball/

    - name: Functional tests
      run: |
        docker-compose up -d;
        sleep 5;  # Allow db to spin up
        docker-compose exec -T app pytest functional_tests/
