name: Test Fantasy Funball

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install poetry
        poetry export --with dev -f requirements.txt --output requirements.txt --without-hashes
        pip install --no-cache-dir -r requirements.txt

    - name: Unit tests
      run: pytest fantasy_funball/

    - name: Functional tests
      run: |
        docker-compose build
        docker-compose up -d;
        sleep 5;  # Allow db to spin up
        docker-compose exec -T app pytest functional_tests/
